services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
