services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - devnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8888:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - devnet
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:

networks:
  devnet:
    driver: bridge
